In [1]:
import numpy as np

In [2]:
second_array = np.identity(4)

In [3]:
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
second_array + 4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [5]:
my_array = np.array([2,14,6,8])

In [6]:
my_array

array([ 2, 14,  6,  8])

In [7]:
my_array - second_array

array([[ 1., 14.,  6.,  8.],
       [ 2., 13.,  6.,  8.],
       [ 2., 14.,  5.,  8.],
       [ 2., 14.,  6.,  7.]])

In [8]:
second_array/my_array

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.07142857, 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        ],
       [0.        , 0.        , 0.        , 0.125     ]])

In [9]:
x = np.arange(3,7,0.5)

In [10]:
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [11]:
x = np.linspace(1.2, 40.5, num=20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

In [12]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

array([ True, False, False,  True])

In [13]:
np.array_equal(x,y)

False

In [14]:
x<y

array([False,  True,  True, False])

In [15]:
x = np.array([0,1,0,0], dtype=bool)
y = np.array([1,1,0,1], dtype=bool)
np.logical_or(x,y)

array([ True,  True, False,  True])

In [16]:
x

array([False,  True, False, False])

In [17]:
y

array([ True,  True, False,  True])

In [18]:
np.logical_and(x,y)

array([False,  True, False, False])

In [19]:
x = np.array([1,2,3,4])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [20]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [21]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [22]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [25]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [27]:
np.sum(x)

15

In [28]:
np.amin(x)

0

In [29]:
np.amax(x)

5

In [30]:
np.amin(x, axis = 0)

array([0, 1, 2])

In [31]:
np.amin(x, axis = 1)

array([0, 3])

In [32]:
np.percentile(x,90)

4.5

In [33]:
x = np.array([1,-21,3,-3])
np.argmax(x)

2

In [34]:
np.argmin(x)

1

In [35]:
x = np.array([[2,3,5],[20,12,4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [36]:
np.mean(x)

7.666666666666667

In [37]:
np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [38]:
np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [39]:
np.median(x)

4.5

In [40]:
np.std(x)

6.394442031083626