In [1]:
import numpy as np

When you have a linear line, you take the derivative so the derivative shows the slope of this line. Gradient is a generalization of the derivative when you have a multiple variable in your function, therefore the result of gradient is actually a vector function rather than a scalar value in derivative. The main goal of ML is actually finding the best model that fits your data. You can evaluate the meaning of the best as minimizing your loss function or objective function. Gradient is used for finding the value of the coefficients or a function that will minimize your loss or cost function. A well-known way of finding optimum points is taking the derivative of the objective function then setting it to zero to find your model coefficients. If you have more than one coefficient then it becomes a gradient rather than a derivative, and it becomes a vector equation rather than a scalar value. You can interpret a gradient as a vector at every point, which is directed to a next local minimum for your function.

In [2]:
a = np.array([1,3,6,7,11,14])
a

array([ 1,  3,  6,  7, 11, 14])

In [3]:
gradient = np.gradient(a)
gradient

array([2. , 2.5, 2. , 2.5, 3.5, 3. ])

In [4]:
## 2-D 
b = np.array([1,3,6,7,11,14]).reshape(2,3)
gradient = np.gradient(b)
b

array([[ 1,  3,  6],
       [ 7, 11, 14]])

In [5]:
gradient #row-direction and column-direction

[array([[6., 8., 8.],
        [6., 8., 8.]]),
 array([[2. , 2.5, 3. ],
        [4. , 3.5, 3. ]])]