In [1]:
import numpy as np

In [2]:
A = np.array([[2,1,2], [3,2,1], [0,1,1]])
A

array([[2, 1, 2],
       [3, 2, 1],
       [0, 1, 1]])

In [3]:
B = np.array([8,3,4])

In [4]:
B

array([8, 3, 4])

In [5]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 0.2,  0.2, -0.6],
       [-0.6,  0.4,  0.8],
       [ 0.6, -0.4,  0.2]])

In [6]:
np.dot(A_inverse, B)

array([-0.2, -0.4,  4.4])

In [7]:
#same calculation with linalg.solve()
x = np.linalg.solve(A, B)
x

array([-0.2, -0.4,  4.4])

In [8]:
#use np.allclose() to compare two arrays element-wise
np.allclose(np.dot(A, x), B)

True

In [9]:
## Linear Regression
from numpy import arange, array, ones, linalg
x = arange(1,11)
A = np.vstack([x, ones(len(x))])
A

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [10]:
A = A.T
A

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.]])

In [11]:
A.shape

(10, 2)

In [12]:
y = [5, 6, 6.5, 7, 8,9.5, 10, 10.4,13.1,15.5] 

In [13]:
len(y)

10

In [14]:
w = linalg.lstsq(A, y)[0]
w

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([1.05575758, 3.29333333])

In [15]:
line = w[0]*x + w[1]*1

array([ 4.34909091,  5.40484848,  6.46060606,  7.51636364,  8.57212121,
        9.62787879, 10.68363636, 11.73939394, 12.79515152, 13.85090909])