In [1]:
import numpy as np

### Vector and matrix mathematics

In [2]:
a = np.arange(6).reshape(3,2)
b = np.arange(10).reshape(2,5)

In [3]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
np.dot(a,b)

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [6]:
np.matmul(a,b)

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [7]:
a@b

array([[ 5,  6,  7,  8,  9],
       [15, 20, 25, 30, 35],
       [25, 34, 43, 52, 61]])

In [8]:
%timeit np.dot(a,b)

1.1 µs ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
%timeit np.matmul(a,b)

1.01 µs ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
%timeit a@b

968 ns ± 16.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
from numpy.linalg import multi_dot

In [12]:
a = np.arange(12).reshape(4,3)
b = np.arange(15).reshape(3,5)
c = np.arange(25).reshape(5,5)

In [13]:
multi_dot([a,b,c])

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [14]:
%timeit multi_dot([a,b,c])

5.04 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
a.dot(b).dot(c)

array([[ 1700,  1855,  2010,  2165,  2320],
       [ 5300,  5770,  6240,  6710,  7180],
       [ 8900,  9685, 10470, 11255, 12040],
       [12500, 13600, 14700, 15800, 16900]])

In [16]:
%timeit a.dot(b).dot(c)

1.63 µs ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
a = np.arange(9).reshape(3,3)

In [18]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
b = np.arange(3)

In [20]:
b

array([0, 1, 2])

In [21]:
np.inner(a,b)

array([ 5, 14, 23])

In [22]:
np.outer(a,b)

array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16]])

In [23]:
###Tensordot
# A tensor is a generic mathematical object of vectors and matrices that can keep the relationships of vectors in high-dimensional spaces
a = np.arange(24
             ).reshape(2,3,4)
b = np.arange(48).reshape(3,2,8)
c = np.tensordot(a,b, axes=([1,0],[0,1]))

In [24]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [26]:
c

array([[1600, 1660, 1720, 1780, 1840, 1900, 1960, 2020],
       [1720, 1786, 1852, 1918, 1984, 2050, 2116, 2182],
       [1840, 1912, 1984, 2056, 2128, 2200, 2272, 2344],
       [1960, 2038, 2116, 2194, 2272, 2350, 2428, 2506]])