In [1]:
import numpy as np

## Loading and saving files

In [2]:
example_array = np.arange(12).reshape(3,4)
example_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.save('example.npy', example_array) #binary file

In [4]:
d = np.load('example.npy')

In [5]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
#Similarly, you can use the savez() function to save several arrays into a single file. 
#If you want to save your files as compressed NumPy binary files, you can use savez_compressed() as follows
x = np.arange(10)
y = np.arange(12)
np.savez('second_example.npz', x, y)

In [7]:
npzfile = np.load('second_example.npz')
npzfile.files

['arr_0', 'arr_1']

In [8]:
npzfile['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
npzfile['arr_1']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.savez_compressed('compressed_example.npz', first_array = x, second_array = y)
npzfile = np.load('compressed_example.npz')
npzfile.files

['first_array', 'second_array']

In [13]:
npzfile['first_array']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
npzfile['second_array']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## EDA

In [15]:
from sklearn.datasets import load_boston
dataset = load_boston()
dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [16]:
samples, label, feature_names = dataset.data, dataset.target, dataset.feature_names

In [17]:
samples.shape

(506, 13)

In [18]:
label.shape

(506,)

In [19]:
feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [20]:
samples.dtype

dtype('float64')

In [21]:
label.dtype

dtype('float64')

In [22]:
np.isnan(np.sum(samples))

False

In [23]:
np.isnan(np.sum(label))

False