In [1]:
import numpy as np

In [2]:
c = np.ones((4,4))

In [3]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [5]:
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array #vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [7]:
y = np.arange(15).reshape(5,3)
x = np.arange(10).reshape(5,2)

In [8]:
new_array = np.hstack((y,x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [12]:
from scipy import stats

In [13]:
x = np.random.rand(100,10)
n, min_max, mean, var, skew, jurt = stats.describe(x)

In [14]:
n

100

In [17]:
min_max

(array([0.01685613, 0.01142456, 0.00199498, 0.00209565, 0.00830941,
        0.00375401, 0.0034596 , 0.00779156, 0.00673427, 0.01691644]),
 array([0.99260787, 0.97379713, 0.99932826, 0.99734759, 0.97935172,
        0.97954174, 0.99333696, 0.98914255, 0.99810442, 0.99231704]))

In [20]:
mean

array([0.5223525 , 0.47740379, 0.54635206, 0.51351081, 0.48999496,
       0.46311591, 0.46358852, 0.50037609, 0.50962981, 0.46987387])

In [21]:
var

array([0.09283662, 0.08847775, 0.08680674, 0.08692641, 0.07485737,
       0.08502004, 0.08736189, 0.07412027, 0.09369001, 0.08188965])

In [22]:
skew

array([-0.12045672,  0.16240167, -0.22895202,  0.04958948,  0.09522823,
        0.08583003,  0.14816661, -0.10404602, -0.13322722,  0.23962378])

In [23]:
jurt

array([-1.28516582, -1.19541459, -1.05403227, -1.27165579, -1.17098291,
       -1.19960198, -1.23630008, -0.92365312, -1.31721313, -1.15013646])

In [25]:
new_array = np.vstack((mean, var, skew, jurt, min_max[0], min_max[1]))

In [27]:
new_array.T

array([[ 0.5223525 ,  0.09283662, -0.12045672, -1.28516582,  0.01685613,
         0.99260787],
       [ 0.47740379,  0.08847775,  0.16240167, -1.19541459,  0.01142456,
         0.97379713],
       [ 0.54635206,  0.08680674, -0.22895202, -1.05403227,  0.00199498,
         0.99932826],
       [ 0.51351081,  0.08692641,  0.04958948, -1.27165579,  0.00209565,
         0.99734759],
       [ 0.48999496,  0.07485737,  0.09522823, -1.17098291,  0.00830941,
         0.97935172],
       [ 0.46311591,  0.08502004,  0.08583003, -1.19960198,  0.00375401,
         0.97954174],
       [ 0.46358852,  0.08736189,  0.14816661, -1.23630008,  0.0034596 ,
         0.99333696],
       [ 0.50037609,  0.07412027, -0.10404602, -0.92365312,  0.00779156,
         0.98914255],
       [ 0.50962981,  0.09369001, -0.13322722, -1.31721313,  0.00673427,
         0.99810442],
       [ 0.46987387,  0.08188965,  0.23962378, -1.15013646,  0.01691644,
         0.99231704]])

In [28]:
##Numpy Mask
import numpy.ma as ma

In [29]:
x = np.arange(6)

In [30]:
x.mean()

2.5

In [31]:
x

array([0, 1, 2, 3, 4, 5])

In [32]:
masked_array = ma.masked_array(x, mask = [1,0,0,0,0,0])
masked_array

masked_array(data=[--, 1, 2, 3, 4, 5],
             mask=[ True, False, False, False, False, False],
       fill_value=999999)

In [33]:
masked_array.mean()

3.0

In [34]:
x = np.arange(25, dtype=float).reshape(5,5)
x[x<5] = np.nan

In [35]:
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [37]:
np.where(np.isnan(x))

(array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4]))

In [42]:
#Shift + Tab to View docstring

In [43]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])

In [44]:
### Indexing
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[5]

5

In [46]:
x[-2]

8

In [47]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [48]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x[2:8:2]

array([2, 4, 6])

In [50]:
x = np.reshape(np.arange(16), (4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
x[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [53]:
x[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [54]:
x[[0,1,2],[0,1,3]]

array([ 0,  5, 11])

In [57]:
np.resize(x, (2,2))

array([[0, 1],
       [2, 3]])

In [58]:
np.resize(x, (6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [59]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [60]:
y = np.arange(2).reshape(1,2)

In [61]:
y

array([[0, 1]])

In [62]:
x*y

array([[0, 1],
       [0, 3]])

In [63]:
x = np.ones(16).reshape(4,4)
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [65]:
x * y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])