In [1]:
import numpy as np

In [2]:
c = np.ones((4,4))

In [3]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [5]:
y = np.arange(15).reshape(3,5)
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array #vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [6]:
y = np.arange(15).reshape(5,3)
x = np.arange(10).reshape(5,2)

In [7]:
new_array = np.hstack((y,x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [8]:
from scipy import stats

In [9]:
x = np.random.rand(100,10)
n, min_max, mean, var, skew, jurt = stats.describe(x)

In [10]:
n

100

In [11]:
min_max

(array([0.00451619, 0.01838907, 0.00161355, 0.02038724, 0.01802802,
        0.00618887, 0.01169452, 0.00472307, 0.00952896, 0.00047734]),
 array([0.95043331, 0.9678462 , 0.97614823, 0.97626492, 0.97614542,
        0.99883694, 0.99482988, 0.99231452, 0.99973896, 0.98395797]))

In [12]:
mean

array([0.49917254, 0.48143478, 0.49022169, 0.49937466, 0.53343839,
       0.50527747, 0.55305482, 0.48801458, 0.51302897, 0.47792978])

In [13]:
var

array([0.07003039, 0.08209553, 0.07661983, 0.0741423 , 0.08049256,
       0.08356254, 0.08388604, 0.09162031, 0.09293754, 0.0795622 ])

In [14]:
skew

array([ 0.03640182,  0.14439268,  0.00115133,  0.10863066, -0.14527931,
        0.01880766, -0.2150663 ,  0.03144441, -0.06511919, -0.06443359])

In [15]:
jurt

array([-0.95209501, -1.30823653, -1.12423507, -1.09002952, -1.21911673,
       -1.2191741 , -1.26191084, -1.22147321, -1.26878312, -1.11981293])

In [16]:
new_array = np.vstack((mean, var, skew, jurt, min_max[0], min_max[1]))

In [17]:
new_array.T

array([[ 4.99172544e-01,  7.00303944e-02,  3.64018181e-02,
        -9.52095009e-01,  4.51618523e-03,  9.50433310e-01],
       [ 4.81434777e-01,  8.20955341e-02,  1.44392679e-01,
        -1.30823653e+00,  1.83890672e-02,  9.67846203e-01],
       [ 4.90221685e-01,  7.66198305e-02,  1.15132516e-03,
        -1.12423507e+00,  1.61355056e-03,  9.76148232e-01],
       [ 4.99374660e-01,  7.41422952e-02,  1.08630661e-01,
        -1.09002952e+00,  2.03872405e-02,  9.76264925e-01],
       [ 5.33438392e-01,  8.04925618e-02, -1.45279314e-01,
        -1.21911673e+00,  1.80280242e-02,  9.76145421e-01],
       [ 5.05277475e-01,  8.35625417e-02,  1.88076562e-02,
        -1.21917410e+00,  6.18887281e-03,  9.98836937e-01],
       [ 5.53054824e-01,  8.38860371e-02, -2.15066300e-01,
        -1.26191084e+00,  1.16945197e-02,  9.94829877e-01],
       [ 4.88014578e-01,  9.16203112e-02,  3.14444142e-02,
        -1.22147321e+00,  4.72306875e-03,  9.92314515e-01],
       [ 5.13028968e-01,  9.29375440e-02, -6.511

In [18]:
##Numpy Mask
import numpy.ma as ma

In [19]:
x = np.arange(6)

In [20]:
x.mean()

2.5

In [21]:
x

array([0, 1, 2, 3, 4, 5])

In [22]:
masked_array = ma.masked_array(x, mask = [1,0,0,0,0,0])
masked_array

masked_array(data=[--, 1, 2, 3, 4, 5],
             mask=[ True, False, False, False, False, False],
       fill_value=999999)

In [23]:
masked_array.mean()

3.0

In [24]:
x = np.arange(25, dtype=float).reshape(5,5)
x[x<5] = np.nan

In [25]:
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [26]:
np.where(np.isnan(x))

(array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4]))

In [27]:
#Shift + Tab to View docstring

In [28]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])

In [29]:
### Indexing
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[5]

5

In [31]:
x[-2]

8

In [32]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [33]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x[2:8:2]

array([2, 4, 6])

In [35]:
x = np.reshape(np.arange(16), (4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
x[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [38]:
x[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [39]:
x[[0,1,2],[0,1,3]]

array([ 0,  5, 11])

In [40]:
np.resize(x, (2,2))

array([[0, 1],
       [2, 3]])

In [41]:
np.resize(x, (6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [42]:
###Broadcasting

In [43]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [44]:
y = np.arange(2).reshape(1,2)

In [45]:
y

array([[0, 1]])

In [46]:
x*y

array([[0, 1],
       [0, 3]])

In [47]:
x = np.ones(16).reshape(4,4)
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [49]:
x * y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])