In [1]:
import numpy as np

In [2]:
x = np.array([2,5,9,0])

In [3]:
np.linalg.norm(x, ord=0) # counting the total number of non-zero elements

3.0

In [4]:
#L1 norm
np.linalg.norm(x, ord=1)
# One of the uses of the L1- norm is for the calculation of mean-absolute error (MAE)

16.0

In [5]:
# The L2-norm is the most popular norm. It calculates the length of the vector by applying the Pythagorean theorem
np.linalg.norm(x, ord=2)


10.488088481701515

One of the well-known applications of the L2-norm is the **mean-squared error (MSE)** calculations. As a matrix consists of vectors, similarly, the norm gives the length or size, but the interpretation and computation is slightly different. In previous chapters, you learned about matrix multiplication with vectors. When you multiply the matrix with a vector in the result, you stretch the vector. The norm of the matrix reveals how much that matrix could possibly stretch a vector

In [6]:
a = np.array([3,7,6,-2,-5,4,1,3,-14]).reshape(3,3)

In [7]:
a

array([[  3,   7,   6],
       [ -2,  -5,   4],
       [  1,   3, -14]])

In [8]:
np.linalg.norm(a, ord=1)

24.0

In [9]:
np.linalg.norm(a, np.inf)

18.0

In [10]:
np.linalg.norm(a, ord=2)

15.8325010064061

In [11]:
#The most popular orders are the Manhattan norm and the Euclidean norm

#### Determinant

By definition, the determinant is the scaling factor of a given matrix in linear transformation. 

In [12]:
A = np.array([2,3,1,4]).reshape(2,2)
A

array([[2, 3],
       [1, 4]])

In [13]:
np.linalg.det(A)

5.000000000000001

In [14]:
B = np.array([2,3,5,1,4,8,5,6,2]).reshape(3,3)
B

array([[2, 3, 5],
       [1, 4, 8],
       [5, 6, 2]])

In [15]:
np.linalg.det(B)

-36.0

The determinant of a transformation actually shows the factor of how much the volume will extend or compress. If the determinant of a matrix A equals 2, that means the transformation of this matrix will extend the volume by 2. If you are doing a chain multiplication, you can also calculate how much the volume changes after the transformation. Let's say you multiply two matrices, that means that there will be two transformations. If det(A) = 2 and det(B)=3, the total transformation factor will be multiplied by 6 as det(AB) = det(A)det(B).

### Trace

 By definition, the trace is the sum of diagonal elements of a matrix. In ML models, in most cases, you work with several regression models to explain your data. It's very likely that some of these models explain your data quality more or less the same, therefore in such cases, you always tend to move forward with the simpler model. Whenever you have to do this trade-off, the trace value becomes very valuable for quantifying the complexity.

In [16]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
b = np.arange(27).reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
np.trace(a)

12

In [19]:
np.trace(b)

array([36, 39, 42])